### ISSUE TITLE
Why inverse?

### ISSUE THREAD

**Issue by stolpa4** [Huangying-Zhan/kitti_odom_eval#2]
Hello, in your code you apply inverse to the first frame and then multiply it with the corresponding (i-th) pose matrix to obtain the pose at the frame i. Why not just multiply the i-th pose matrix with the first pose? Why do we need inverse here?

I am talking about the lines like: poses_result[cnt] = np.linalg.inv(pred_0) @ poses_result[cnt].
I thought to obtain poses we simply need to: poses_result[cnt] = poses_result[cnt] @ pred_0.

**Comment by SBaokun** [comment]
Hi, I have the same problem, how did you solve it? Thanks!
