### ISSUE TITLE
why the result is always shrink to a point.?

### ISSUE THREAD

**Issue by xdr940** [Huangying-Zhan/kitti_odom_eval#5]
Using Jiawang's model, I get 09.txt. 
When I apply this code, the result will always shrink to a point.
 Excuse me, what's the matter?

**Comment by xdr940** [comment]
![Screenshot from 2020-06-15 09-11-54](https://user-images.githubusercontent.com/40014131/84609135-474b8a00-aee8-11ea-8a29-d736e55d63c5.png)

**Comment by xdr940** [comment]
![Screenshot from 2020-06-15 09-12-48](https://user-images.githubusercontent.com/40014131/84609164-6ba76680-aee8-11ea-89dc-68409b1e478c.png)

**Comment by Huangying-Zhan** [comment]
Since monocular model is up-to-scale. you may need to apply 7dof alignment by adding this argument
`--align 7dof`

**Comment by xdr940** [comment]
Thanks for your replay !

When I did what you said, it really is no longer like before, but the result still seems wrong. Is this a problem with my poses result? (The poses estimated by model that  Jiawang released  )

![image](https://user-images.githubusercontent.com/40014131/84745276-ef477d00-afe6-11ea-9f87-754ca52f2e5d.png)
![image](https://user-images.githubusercontent.com/40014131/84745329-00908980-afe7-11ea-91e6-024b92a82d92.png)
![image](https://user-images.githubusercontent.com/40014131/84745385-0edea580-afe7-11ea-8257-91364aad55a8.png)
![image](https://user-images.githubusercontent.com/40014131/84745403-1736e080-afe7-11ea-991b-487dea7c8b04.png)
![image](https://user-images.githubusercontent.com/40014131/84745428-21f17580-afe7-11ea-9187-dbac27b9ba01.png)

Thansk for your patience !

**Comment by Huangying-Zhan** [comment]
It looks like the pose result you got is incorrect. Could you double check the result?

**Comment by xdr940** [comment]
> It looks like the pose result you got is incorrect. Could you double check the result?
Ok, I'll  check it out. Thank you anyway !
